// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vmmO5oFQNbBExLFmmF2cixDetU6iIoU',
    appId: '1:811799327109:web:976604e59a28ea9e85d4ec',
    messagingSenderId: '811799327109',
    projectId: 'personal-8bfe8',
    authDomain: 'personal-8bfe8.firebaseapp.com',
    storageBucket: 'personal-8bfe8.firebasestorage.app',
    measurementId: 'G-85F2PD8S9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRU9HQvFdM53oRHqcn08rYD_BfC9StxQ8',
    appId: '1:811799327109:android:313ac0b4198c615385d4ec',
    messagingSenderId: '811799327109',
    projectId: 'personal-8bfe8',
    storageBucket: 'personal-8bfe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwfH0cv2-PqpKUOl7pqZJDAGlt9JQyp8Y',
    appId: '1:811799327109:ios:b8c1d115aef064fe85d4ec',
    messagingSenderId: '811799327109',
    projectId: 'personal-8bfe8',
    storageBucket: 'personal-8bfe8.firebasestorage.app',
    iosBundleId: 'sociacity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwfH0cv2-PqpKUOl7pqZJDAGlt9JQyp8Y',
    appId: '1:811799327109:ios:bcfa2c5433dcf34585d4ec',
    messagingSenderId: '811799327109',
    projectId: 'personal-8bfe8',
    storageBucket: 'personal-8bfe8.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0vmmO5oFQNbBExLFmmF2cixDetU6iIoU',
    appId: '1:811799327109:web:2666fd045b1cd44785d4ec',
    messagingSenderId: '811799327109',
    projectId: 'personal-8bfe8',
    authDomain: 'personal-8bfe8.firebaseapp.com',
    storageBucket: 'personal-8bfe8.firebasestorage.app',
    measurementId: 'G-8G6R84LBDQ',
  );
}
